services:
  openchat:
    #image: ghcr.io/openchatui/openchatui:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"                                     
      NEXTAUTH_URL: "http://localhost:3000"          
      NEXTAUTH_SECRET: "your-secret-here"              
      AUTH_TRUST_HOST: "true"                        
      AUTH: "true"                                     
      #  DB: "sqlite"                                
      #  SQLITE_URL: "file:/prisma/dev.db"             
      #  DATABASE_URL: "postgresql://user:pass@host/db"
      #  NODE_ENV: "production"                        
      #  OPENAI_API_KEY: "sk-..."
      #  ANTHROPIC_API_KEY: "sk-ant-..."
      #  OLLAMA_URL: "http://localhost:11434"
      #  DRIVE_CLIENT_ID: "your-google-client-id"
      #  DRIVE_CLIENT_SECRET: "your-google-client-secret"
    volumes:
      - ./prisma:/prisma
      - ./data:/app/data
      - ./public/profiles:/app/public/profiles
    restart: unless-stopped
